import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import { Sidebar } from "@/components/layout/Sidebar";
import { Roboto_Slab } from 'next/font/google'
import { NavigationProvider } from "@/context/NavigationProvider";


const inter = Roboto_Slab({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto-slab',
})

export const metadata: Metadata = {
  title: "Landspot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} w-full h-full`}>
      <body className="w-full h-full">
        <AuthProvider>
          <div className="w-full h-full grid grid-cols-1 md:grid-cols-[auto_1fr]">
            <NavigationProvider>
              <Sidebar />
              {children}
            </NavigationProvider>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
